### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by matthias-hampel** [SkippyZA/ibt-telemetry#4]
Hello 👋 

I'm very happy that such a library exists 👍  Thanks for creating and maintaining it 👏 

I tried to implement the example from your README, but once I start my project, I get the following error:
```javascript
ReferenceError: regeneratorRuntime is not defined
    at /home/matthias/repos/telemetry-parser/node_modules/ibt-telemetry/lib/telemetry.js:84:25
    at Object.<anonymous> (/home/matthias/repos/telemetry-parser/node_modules/ibt-telemetry/lib/telemetry.js:147:2)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/matthias/repos/telemetry-parser/node_modules/ibt-telemetry/lib/index.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
```

Here is my source code:
```javascript
const Telemetry = require("ibt-telemetry");

const pathToIbt = "telemetry.ibt";
const telemetry = Telemetry.fromFile(pathToIbt);

const telemetryId = telemetry.uniqueId();
```

This is the telemetry file I tried to load: [telemtry.tar.gz](https://github.com/SkippyZA/ibt-telemetry/files/6758389/telemtry.tar.gz)

I hope you can help my solving this problem.

**Comment by SkippyZA** [comment]
Hey. Sorry for the delay in replying.

This library, in the current state in `master`, relies on using babel to transpile the code. This is due to the use of an async generator function.

I am in the process of rewriting the library to use typescript. It is currently available in the branch `to-typescript`. It is in a working state and does not rely on any additional transpiling, which means Typescript handles it straight out of the box

**Comment by SkippyZA** [comment]
Here is a sample of how you can make use of the Typescript branch to process the telemetry. I'll try have it finished and merged as v2 during the next week.

```typescript
import { map } from 'rxjs/operators'
import { Telemetry as IbtTelemetry } from 'ibt-telemetry'

const telemetryFile = 'path to ibt file'

;(async () => {
  console.log('Loading telemetry from:', telemetryFile)
  const t = await IbtTelemetry.fromFile(telemetryFile)

  t.sampleStream()
    .pipe(
      map(s => s.getParam('RPM'))
    )
    .subscribe(
      rpm => console.log('RPM:', rpm?.value),
      err => console.error('Error:', err),
      () => console.log('Finished processing telemetry')
    )
})()
```
