### ISSUE TITLE
Help getting it to work

### ISSUE THREAD

**Issue by Sergih28** [SkippyZA/ibt-telemetry#5]
Hi,

I've spent several hours trying to get this to work, but I just can't.
Could you please guide me on how to get this up and running with an ibt file?

Thanks!

**Comment by SkippyZA** [comment]
Hey @Sergih28. The master of this library currently require Babel to transform the async generator function. This didn't work out well so I have been rewriting it to use typescript and rxjs.

Please try out the typescript branch and example as described here: https://github.com/SkippyZA/ibt-telemetry/issues/4

I'll be merging and releasing v2 of the library soon which will be from that branch.

Hope this helps

**Comment by Sergih28** [comment]
Hey @SkippyZA. Maybe I'm lost on some of the basic stuff but I still can't make this work.
Here's what I've done:
1. Clone the repo
2. Go to the `to-typescript` branch
3. `npm install`
4. (`npm run build`)
5. I create a new file (`newfile.js`) in the root of the project and paste the code in #4 
6.  Run `node newfile.js`
6. Fix _package.json_ complaining about modules with `"type": "module"`
7. Run `node newfile.js`
8. Then the big error comes. If I try to fix whatever it's complaining, I eventually end up nowhere.
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/sergi/Documents/ibt-telemetry/node_modules/rxjs/operators' is not supported resolving ES modules imported from /Users/sergi/Documents/ibt-telemetry/newfile.js
Did you mean to import rxjs/operators/index.js? 
```

Sorry for my lack of knowledge, but this is the best info I can provide.
Thank you for your help 😀

**Comment by SkippyZA** [comment]
As this is a typescript project, it wasn't meant for a mixture of JS+TS in the repo itself. Once published, this will be better.

The best thing to do is remove the `"type": "module"` from the `package.json` and rather change your `newfile.js` to use `require` instead of `import`. Here is a working example:

```typescript
const { map } = require('rxjs/operators')
const { Telemetry } = require('./dist')
const IbtTelemetry = Telemetry

const telemetryFile = './test/dallaraf3_montreal-1.ibt'

;(async () => {
  console.log('Loading telemetry from:', telemetryFile)
  const t = await IbtTelemetry.fromFile(telemetryFile)

  t.sampleStream()
    .pipe(
      map(s => s.getParam('RPM'))
    )
    .subscribe(
      rpm => console.log('RPM:', rpm?.value),
      err => console.error('Error:', err),
      () => console.log('Finished processing telemetry')
    )
})()
```

**Comment by SkippyZA** [comment]
Oh, also note that there is no `npm run build`, but rather `npm run compile` which needs to be done to build the TypeScript to javascript

**Comment by Sergih28** [comment]
I meant `rpm run compile` not `npm run build` sorry.

Okay so with that code it worked!

Thank you for your help 😃
