### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by niklasden** [SkippyZA/ibt-telemetry#6]
Hi there,

fist off, thank your for all the work you have put into this project so far.

Are you still maintaining this?
I got the current code to run, but I can not wrap my head around the generator function to get the individual samples from the telemetry feed. Can you explain to me, how to iterate through the samples?

Best regards,
Niklas

**Comment by SkippyZA** [comment]
Hi @niklasden.

I started rewriting this to use TypeScript without the async generator. It is in a working state, but there is likely going to be changes to it before I officially release it. I tend to work on this on occasion.

If you take a look at this issue: https://github.com/SkippyZA/ibt-telemetry/issues/4 I discuss how to use the `to-typescript` branch which does not require the transpilation with babel to make use of the async generators.

There is also this comment https://github.com/SkippyZA/ibt-telemetry/issues/1#issuecomment-568279412, which mentions how to include the polyfill to make the existing version work.
